name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
      - run: pnpm install --no-frozen-lockfile && pnpm build && pnpm plugin-zip
      - uses: actions/upload-artifact@v2
        with:
          name: plugin
          path: hikaeptm.zip
